### ISSUE TITLE
BUG - Fetching new access token breaks python code on 401

### ISSUE THREAD

**Issue by gbadnmo** [pinterest/pinterest-python-sdk#114]
**Describe the bug**
 

**To Reproduce**

Executing the following code where the refresh token is invalid or has the wrong grants 
```
refresh_token = 'pinr.<REDACTED>'
client_id = '<REDACTED>'
client_secret = '<REDACTED>'

from pinterest.client import PinterestSDKClient
client = PinterestSDKClient.create_client_with_refresh_token(refresh_token, app_id=client_id, app_secret=client_secret)
```

Yields the error :
`AttributeError: 'HTTPResponse' object has no attribute 'body'. Did you mean: '_body'?`

**Expected behavior**
 
It should throw an error the SdkException in pinterest.utils.refresh_access_token.get_new_access_token with `b'{"code":283,"message":"The authorization grant is invalid"}'` 

**Screenshots**
 
-

**Additional Details (please complete the following information):**
 
 - OS and Version: Linux
 - SDK Version v0.2.1

**Additional Context**

**Comment by Igosuki** [comment]
Thanks :+1:
