### ISSUE TITLE
BUG - Campaign Lifetime Budget Updates Does Not Send List

### ISSUE THREAD

**Issue by jena-cameron** [pinterest/pinterest-python-sdk#139]
**Describe the bug**

The [Lifetime Budget](https://github.com/pinterest/pinterest-python-sdk/blob/72f3c2ab15ef87754c732aa4f06520ba50c5b3c9/pinterest/ads/campaigns.py#L379) update fails because it does not wrap the CampaignUpdateRequest in a list like the [Daily Budget](https://github.com/pinterest/pinterest-python-sdk/blob/72f3c2ab15ef87754c732aa4f06520ba50c5b3c9/pinterest/ads/campaigns.py#L401) update.

If a Life time budget update is attempted we receive the following error:
`Invalid type for variable 'campaign_update_request'. Required value type is list and passed type was CampaignUpdateRequest at ['campaign_update_request']`

**To Reproduce**
 
1. The model/class with an issue is  pinterest/ads/Campaigns.py
2. The function with an issue is set_lifetime_budget(self, new_spend_cap:int)
3. The arguments passed to the model/function are any positive integer value
4. The error thrown is '`Invalid type for variable 'campaign_update_request'. Required value type is list and passed type was CampaignUpdateRequest at ['campaign_update_request']`

**Expected behavior**
 
I would expect the CampaignUpdateRequest object to be wrapped in a list object like the set_daily_budget function in the same class.

**Screenshots**
 
<img width="469" alt="Screenshot 2024-10-09 at 10 48 47 AM" src="https://github.com/user-attachments/assets/c9952229-74fb-43cb-b57b-bc3a8533ce60">

**Additional Details (please complete the following information):**
 
 - OS and Version: MacOS and Windows
 - SDK Version [all versions]

**Additional Context**
n/a

**Comment by t20** [comment]
Fixed in #140 
Made a new release. Available in pinterest-api-sdk==0.2.4
